ProyectoFinalDIW/ProyectoFinalDIW/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinalDIW.Models;
using ProyectoFinalDIW.Servicios;
using System.Globalization;

namespace ProyectoFinalDIW.Controllers
{
    /// <summary>
    /// Controlador para gestionar la administracion de usuarios y de suplementos
    /// </summary>
    /// autor: Fran Gallego
    public class AdminController : Controller
    {
        // Inicializamos la interfaz Usuario y Suplemento para usar sus métodos
        private UsuarioInterfaz usuarioInterfaz = new UsuarioImplementacion();
        private SuplementoInterfaz suplementoInterfaz = new SuplementoImplementacion();

        /// <summary>
        /// Método que devuelve la vista de administracion usuarios
        /// </summary>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaAdministracionUsuario()
        {
            try
            {
                // Log
                Util.LogInfo("AdminController", "VistaAdministracionUsuario", "Ha entrado en VistaAdministracionUsuario");

                // Controlamos si el usuario iniciado es admin
                if (!Util.ControlaSesionAdmin(HttpContext))
                {
                    // Si no es admin redirigimos a la vista login
                    return RedirectToAction("VistaLogin", "Login");
                }

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Obtenemos una lista con todos los usuarios y ordenamos por el acceso del usuario
                List<UsuarioDTO> listaUsuarios = usuarioInterfaz.ObtieneTodosLosUsuarios()
                                                                .Result
                                                                .OrderBy(u => u.Id_acceso == 2 ? 0 : 1)
                                                                .ToList();

                // Devolvemos la vista con la lista de los usuarios
                return View(listaUsuarios);
            }
            catch (Exception)
            {
                // Log
                Util.LogError("AdminController", "VistaAdministracionUsuario", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que devuelve la vista administracion de suplementos
        /// </summary>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaAdministracionProducto()
        {
            try
            {
                // Log
                Util.LogInfo("AdminController", "VistaAdministracionProducto", "Ha entrado en VistaAdministracionProducto");

                // Controlamos si el usuario es admin
                if (!Util.ControlaSesionAdmin(HttpContext))
                {
                    // Si no es admin redirigimos a login
                    return RedirectToAction("VistaLogin", "Login");
                }

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Obtenemos una lista con todos los suplementos
                List<SuplementoDTO> listaSuplementos = suplementoInterfaz.ObtieneTodosLosSuplementos().Result;

                // Devolvemos la vista con la lista de suplementos
                return View(listaSuplementos);
            }
            catch (Exception)
            {
                // Log
                Util.LogError("AdminController", "VistaAdministracionProducto", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que devuelve la vista de editar usuario
        /// </summary>
        /// <param name="id">Id del usuario a mostrar</param>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaEditarUsuario(int id)
        {
            try
            {
                // Log
                Util.LogInfo("AdminController", "VistaEditarUsuario", "Ha entrado en VistaEditarUsuario");

                // Controlamos si el usuario es admin
                if (!Util.ControlaSesionAdmin(HttpContext))
                {
                    // Si el usuario no es admin redirigimos a login
                    return RedirectToAction("VistaLogin", "Login");
                }

                // Obtenemos el usuario por el id
                UsuarioDTO usuario = usuarioInterfaz.BuscaUsuarioPorId(id).Result;

                // Si el usuario es null redirigimos a home
                if (usuario == null)
                    return RedirectToAction("Index", "Home");

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Devolvemos la vista con el usuario
                return View(usuario);
            }
            catch (Exception)
            {
                // Log
                Util.LogError("AdminController", "VistaEditarUsuario", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que devuelve la vista editar suplemento
        /// </summary>
        /// <param name="id">Id del suplemento a mostrar</param>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaEditarSuplemento(int id)
        {
            try
            {
                // Log
                Util.LogInfo("AdminController", "VistaEditarSuplemento", "Ha entrado en VistaEditarSuplemento");

                // Controlamos si el usuario es admin
                if (!Util.ControlaSesionAdmin(HttpContext))
                {
                    // Si no es admin redirigimos a login
                    return RedirectToAction("VistaLogin", "Login");
                }

                // Obtenemos el suplemento por el id
                SuplementoDTO suplemento = suplementoInterfaz.BuscaSuplementoPorId(id).Result;

                // Si el suplemento es null redirigimos a home
                if (suplemento == null)
                    return RedirectToAction("Index", "Home");

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Devolvemos la vista con el suplemento
                return View(suplemento);
            }
            catch (Exception)
            {
                // Log
                Util.LogError("AdminController", "VistaEditarSuplemento", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que devuelve la vista para agregar un suplemento
        /// </summary>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaAgregarSuplemento()
        {
            try
            {
                // Log
                Util.LogInfo("AdminController", "VistaAgregarSuplemento", "Ha entrado en VistaAgregarSuplemento");

                // Controlamos si el usuario es admin
                if (!Util.ControlaSesionAdmin(HttpContext))
                {
                    // Si no es admin redirigimos a login
                    return RedirectToAction("VistaLogin", "Login");
                }

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Creamos un opbjeto suplemento
                SuplementoDTO suplemento = new SuplementoDTO();

                // Devolvemos la vista con el suplemento creado
                return View(suplemento);
            }
            catch (Exception)
            {
                // Log
                Util.LogError("AdminController", "VistaAgregarSuplemento", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que devuelve la vista para agregar usuario
        /// </summary>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaAgregarUsuario()
        {
            try
            {
                // Log
                Util.LogInfo("AdminController", "VistaAgregarUsuario", "Ha entrado en VistaAgregarUsuario");

                // Controlamos si el usuario es admin
                if (!Util.ControlaSesionAdmin(HttpContext))
                {
                    // Si no es admin redirigimos a la vista login
                    return RedirectToAction("VistaLogin", "Login");
                }

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Creamos un objeto usuario
                UsuarioDTO usuarioDTO = new UsuarioDTO();

                // Devolvemos la vista con el usuario creado
                return View(usuarioDTO);
            }
            catch (Exception)
            {
                // Log
                Util.LogError("AdminController", "VistaAgregarUsuario", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        // Métodos

        /// <summary>
        /// Método que realiza el borrado de un usuario
        /// </summary>
        /// <param name="id">Id del usuario a borrar</param>
        /// <returns>Devuelve una redireccion</returns>
        public ActionResult BorrarUsuario(int id)
        {
            try
            {
                // Log
                Util.LogInfo("AdminController", "BorrarUsuario", "Ha entrado en BorrarUsuario");

                // Controlamos si el usuario es admin
                if (!Util.ControlaSesionAdmin(HttpContext))
                {
                    // Si no es admin redirigimos a la vista login

ProyectoFinalDIW/ProyectoFinalDIW/Controllers/NutricionController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinalDIW.Models;
using ProyectoFinalDIW.Servicios;

namespace ProyectoFinalDIW.Controllers
{
	/// <summary>
	/// Controlador para la vista de nutricon
	/// </summary>
	/// autor: Fran Gallego
    public class NutricionController : Controller
    {
		// Inicializamos la interfaz Carrito para usar sus métodos
		private CarritoInterfaz carritoInterfaz = new CarritoImplementacion();

        // Inicializamos la interfaz Suplemento para usar sus métodos
        private SuplementoInterfaz suplementoInterfaz = new SuplementoImplementacion();

		/// <summary>
		/// Método que devuelve la vista de suplementos
		/// </summary>
		/// <param name="st">Tipo de suplemento a mostrar (1: Proteína; 2: Creatina; 3: Todo)</param>
		/// <returns>Devuelve una vista</returns>
        public IActionResult VistaSuplementos(int st)
        {
			try
			{
                // Log
                Util.LogInfo("NutricionController", "VistaSuplementos", "Ha entrado en VistaSuplementos");

                // Controlamos si el usuario ha iniciado sesion o no
                if (!Util.ControlaSesion(HttpContext))
                {
                    // Redireccionamos a la vista de login
                    return RedirectToAction("VistaLogin", "Login");
                }

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Obtenemos todos los suplementos
                List<SuplementoDTO> listaSuplementos = suplementoInterfaz.ObtieneTodosLosSuplementos().Result;

                // Ahora filtramos la lista por el tipo de suplemento
                if (st == 1)
                {
                    // Proteínas
                    listaSuplementos = listaSuplementos.Where(suplemento => suplemento.Tipo_suplemento == "Proteína").ToList();
                }
                else if (st == 2)
                {
                    // Creatinas
                    listaSuplementos = listaSuplementos.Where(suplemento => suplemento.Tipo_suplemento == "Creatina").ToList();
                }

                // Devolvemos la vista con los suplementos
                return View(listaSuplementos);
            }
			catch (Exception)
			{
                // Log
                Util.LogError("NutricionController", "VistaSuplementos", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

		/// <summary>
		/// Método para agregar un suplemento al carrito
		/// </summary>
		/// <param name="id_suplemento">Id del suplemento a agregar</param>
		/// <returns>Devuelve una redireccion</returns>
        public ActionResult AgregaSuplementoCarrito(long id_suplemento)
		{
			try
			{
                // Log
                Util.LogInfo("NutricionController", "AgregaSuplementoCarrito", "Ha entrado en AgregaSuplementoCarrito");

                // Control de sesión
                if (!Util.ControlaSesion(HttpContext))
				{
					return RedirectToAction("VistaLogin", "Login");
				}

				ViewData["acceso"] = HttpContext.Session.GetString("acceso");

				// Obtenemos el email del usuario
				string email = HttpContext.Session.GetString("email")!;

				// Agregamos el suplemento al carrito
				bool agregado = carritoInterfaz.AgregaSuplemento(id_suplemento, email);

				// Controlamos si se ha agregado correctamente o no
				if(agregado)
					TempData["suplementoAgregado"] = "El suplemento se ha agregado al carrito con éxito!";
				else
					TempData["suplementoError"] = "El suplemento no se ha podido agregar al carrito!";

				// Redirigimos a la vista suplementos
				return RedirectToAction("VistaSuplementos");
			}
			catch (Exception)
			{
                // Log
                Util.LogError("NutricionController", "AgregaSuplementoCarrito", "Se ha producido un error");

                TempData["suplementoError"] = "El suplemento no se ha podido agregar al carrito!";
				return RedirectToAction("VistaSuplementos");
			}
		}
	}
}

ProyectoFinalDIW/ProyectoFinalDIW/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinalDIW.Models;
using ProyectoFinalDIW.Servicios;

namespace ProyectoFinalDIW.Controllers
{
    /// <summary>
    /// Controlador para la vista perfil
    /// </summary>
    /// autor: Fran Gallego
    public class PerfilController : Controller
    {
        // Inicializamos la interfaz de Usuario para usar sus métodos
        private UsuarioInterfaz usuarioInterfaz = new UsuarioImplementacion();

        /// <summary>
        /// Método que devuelve la vista perfil
        /// </summary>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaPerfil()
        {
            try
            {
                // Log
                Util.LogInfo("PerfilController", "VistaPerfil", "Ha entrado en VistaPerfil");

                // Control de sesión
                if (!Util.ControlaSesion(HttpContext))
                    return RedirectToAction("VistaLogin", "Login");

                ViewData["acceso"] = HttpContext.Session.GetString("acceso");

                // Obtenemos el email
                string email = HttpContext.Session.GetString("email")!;

                // Obtenemos el usuario por el email
                UsuarioDTO usuarioEncontrado = usuarioInterfaz.BuscaUsuarioPorEmail(email).Result;

                // Devolvemos la vista con el usuario
                return View(usuarioEncontrado);
            }
            catch (Exception)
            {
                // Log
                Util.LogError("PerfilController", "VistaPerfil", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método para realizar el cierre de sesion
        /// </summary>
        /// <returns>Devuelve una redireccion</returns>
        public IActionResult CerrarSesion()
        {
            try
            {
                // Log
                Util.LogInfo("PerfilController", "CerrarSesion", "Ha entrado en CerrarSesion");

                // Control de sesión
                if (!Util.ControlaSesion(HttpContext))
                    return RedirectToAction("VistaLogin", "Login");

                // Cambiamos el acceso a 0
                HttpContext.Session.SetString("acceso", "0");

                // Mensaje de cierre de sesion con exito
                TempData["sesionCerrada"] = "Se ha cerrado sesión con éxito!!";

                // Redirigimos a la vista login
                return RedirectToAction("VistaLogin", "Login");
            }
            catch (Exception)
            {
                // Log
                Util.LogError("PerfilController", "CerrarSesion", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }
    }
}

ProyectoFinalDIW/ProyectoFinalDIW/Views/Shared/VistaBienvenida.cshtml
@{
    ViewData["Title"] = "Bienvenida";
}

ProyectoFinalDIW/ProyectoFinalDIW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFinalDIW</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" asp-append-version="true">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous" asp-append-version="true"></script>
    <!-- Fin Bootstrap -->
    <!-- CSS -->
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/css/styleLogin.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/ProyectoFinalDIW.styles.css" asp-append-version="true" />
    <!-- Fin CSS -->
    <!-- Font awesome -->
    <link href="https://cdn.jsdelivr.net/gh/eliyantosarage/font-awesome-pro@main/fontawesome-pro-6.5.1-web/css/all.min.css"
          rel="stylesheet" asp-append-version="true">
    <!-- Fin Font awesome -->
    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" asp-append-version="true"></script>
    <!-- Fin SweetAlert2 -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg"
             style="background: linear-gradient(90deg, rgba(141,148,241,1) 0%, rgba(157,141,241,1) 49%, rgba(181,141,241,1) 100%);;">
            <div class="container-fluid">
                <img src="~/img/logo2.png" alt="Logo" width="40" height="40" class="d-inline-block align-text-top">
                <a class="navbar-brand text-white nombreTiendaSuplementos">Tienda de Suplementos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-top: 5px;">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active text-white" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active text-white" aria-current="page" href="@Url.Action("VistaSuplementos", "Nutricion")">Nutrición</a>
                        </li>
                        @if (ViewData["acceso"].ToString() == "2")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Admin" asp-action="VistaAdministracionUsuario">Administración</a>
                            </li>
                        }
                        <li class="nav-item perfilLink">
							<a asp-controller="Carrito" asp-action="VistaCarrito" class="nav-link text-white">Carrito</a>
						</li>
                        <li class="nav-item perfilLink">
                            <a asp-controller="Perfil" asp-action="VistaPerfil" class="nav-link text-white">Perfil</a>
                        </li>
                    </ul>
                    <a asp-controller="Carrito" asp-action="VistaCarrito" class="carrito"><i class="fa-regular fa-cart-shopping"></i></a>
                    <a asp-controller="Perfil" asp-action="VistaPerfil" class="iconoPerfil"><i class="fa-solid fa-user"></i></a>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>