ProyectoFinalDIW/ProyectoFinalDIW/Controllers/ActivaCuentaController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinalDIW.Models;
using ProyectoFinalDIW.Servicios;

namespace ProyectoFinalDIW.Controllers
{
    /// <summary>
    /// Controlador que gestiona el activar cuenta
    /// </summary>
    /// autor: Fran Gallego
    public class ActivaCuentaController : Controller
    {
        // Inicializamos la interfaz Usuario para usar sus métodos
        private UsuarioInterfaz usuarioInterfaz = new UsuarioImplementacion();

        // Inicializamos la interfaz Token para usar sus métodos
        private TokenInterfaz tokenInterfaz = new TokenImplementacion();

        /// <summary>
        /// Método para mostrar la vista de confirmacion de email
        /// </summary>
        /// <returns>Devuelve la vista</returns>
        public IActionResult VistaConfirmaEmail()
        {
            try
            {
                // Log
                Util.LogInfo("ActivaCuentaController", "VistaConfirmaEmail", "Ha entrado en VistaConfirmaEmail");

                // Controlamos la sesion, si el usuario ha iniciado sesión redirigimos a Home
                if (Util.ControlaSesion(HttpContext))
                {
                    return RedirectToAction("Index", "Home");
                }

                // Si el usuario no ha iniciado sesión devolvemos la vista
                return View();
            }
            catch (Exception)
            {
                // Log
                Util.LogError("ActivaCuentaController", "VistaConfirmaEmail", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que realiza la activacion de una cuenta
        /// </summary>
        /// <param name="tokenForm">Token</param>
        /// <returns>Devuelve una redireccion</returns>
        [HttpPost]
        public ActionResult ConfirmaEmail(String tokenForm)
        {
            try
            {
                // Log
                Util.LogInfo("ActivaCuentaController", "ConfirmaEmail", "Ha entrado en ConfirmaEmail");

                // Obtenemos el token de la base de datos
                TokenDTO tokenDto = tokenInterfaz.ObtenerToken(tokenForm).Result;

                // Controlamos si el token es válido o no
                // Será válido si es distinto de null y la fecha límite del token no se ha pasado
                // Obtenemos la fecha actual
                DateTime fecha = DateTime.Now;
                if (tokenDto == null)
                {
                    TempData["Mensaje"] = "El token no existe!!";
                    return RedirectToAction("VistaConfirmaEmail", new { tk = tokenForm });
                }
                else if (tokenDto.Fch_fin_token < fecha)
                {
                    TempData["Mensaje"] = "El token ha caducado!!";
                    return RedirectToAction("VistaConfirmaEmail", new { tk = tokenForm });
                }

                // Si llega aqui es porque el token es valido
                // Luego llamamos al método activar cuenta y le pasamos los parámetros
                bool ok = usuarioInterfaz.ActivaCuenta(tokenDto);

                // Controlamos si se ha activado la cuenta correctamente
                if (ok)
                {
                    // Se ha activado la cuenta correctamente
                    TempData["MensajeCorrecto"] = "Se ha activado la cuenta correctamente!!";
                    return RedirectToAction("VistaConfirmaEmail", new { tk = tokenForm });
                }
                else
                {
                    TempData["Mensaje"] = "Ha ocurrido un error, vuelve a intentarlo más tarde!!";
                    return RedirectToAction("VistaConfirmaEmail", new { tk = tokenForm });
                }
            }
            catch (Exception)
            {
                // Log
                Util.LogError("ActivaCuentaController", "ConfirmaEmail", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }
    }
}

ProyectoFinalDIW/ProyectoFinalDIW/Views/ActivaCuenta/VistaConfirmaEmail.cshtml
@{
    ViewData["Title"] = "Confirmar Email";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Tienda de Suplementos</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    @*     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script> *@
    <!-- Fin Bootstrap -->
    <!-- CSS -->
    <link rel="stylesheet" href="~/css/styleLogin.css" />
    <!-- Fin CSS -->
    <!-- Font awesome -->
    <link href="https://cdn.jsdelivr.net/gh/eliyantosarage/font-awesome-pro@main/fontawesome-pro-6.5.1-web/css/all.min.css" rel="stylesheet">
    <!-- Fin Font awesome -->
</head>
<body>
    <div class="wrapper">
        <form method="post" asp-controller="ActivaCuenta" asp-action="ConfirmaEmail" id="formularioMod">
            <h1>Confirmar cuenta</h1>
            <h4>Para activar la cuenta pulse el botón.</h4>
            <input type="text" name="tokenForm" style="display: none" value="" id="idToken">

            @if (TempData["Mensaje"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["Mensaje"]
                </div>
            }

            @if (TempData["MensajeCorrecto"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @TempData["MensajeCorrecto"]
                </div>
            }
            
            <button type="submit" class="boton">Activar</button>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const urlParams = new URLSearchParams(window.location.search).get("tk");
            const idTokenInput = document.getElementById('idToken');
            idTokenInput.value = urlParams;
        });
    </script>
</body>
</html>