ProyectoFinalDIW/ProyectoFinalDIW/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinalDIW.Models;
using ProyectoFinalDIW.Servicios;

namespace ProyectoFinalDIW.Controllers
{
    /// <summary>
    /// Controlador para gestionar el inicio de sesión
    /// </summary>
    /// autor: Fran Gallego
    public class LoginController : Controller
    {
        // Inicializamos la intefaz Usuario para usar sus métodos
        private UsuarioInterfaz usuarioInterfaz = new UsuarioImplementacion();

        /// <summary>
        /// Método para mostrar la vista de login
        /// </summary>
        /// <returns>Devuelve la vista</returns>
        public IActionResult VistaLogin()
        {
            try
            {
                // Log
                Util.LogInfo("LoginController", "VistaLogin", "Ha entrado en VistaLogin");

                // Verificamos si el usuario ya ha iniciado sesión
                if (Util.ControlaSesion(HttpContext))
                {
                    // Si ha iniciado sesión redirigimos a Home
                    return RedirectToAction("Index", "Home");
                }

                // Devolvemos la vista
                return View();
                // Tambien podriamos poner:
                // return View("~/Views/Login/VistaLogin.cshtml");
            }
            catch (Exception)
            {
                // Log
                Util.LogError("LoginController", "VistaLogin", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método para realizar el inicio de sesión
        /// </summary>
        /// <param name="usuario">Objeto UsuarioDTO con los datos del usuario</param>
        /// <returns>Devuelve la vista de login en caso de error o una redirección a Home</returns>
        [HttpPost]
        public ActionResult LoginUsuario(UsuarioDTO usuario)
        {
            try
            {
                // Log
                Util.LogInfo("LoginController", "LoginUsuario", "Ha entrado en LoginUsuario");

                // Verificamos si el usuario está incompleto
                if (usuario.Psswd_usuario == null || usuario.Email_usuario == null)
                {
                    // ViewData nos permite enviar datos del controlador a la vista
                    ViewData["Mensaje"] = "Tienes que rellenar todos los datos!!";
                    return View("VistaLogin");
                }

                // Si todos los datos están completos hacemos el inicio de sesión
                UsuarioDTO usuarioEncontrado = usuarioInterfaz.LoginUsuario(usuario);

                // Si el usuario devuelto es distinto de null y su propiedad estaActivado_usuario es true
                // se ha realizado el inicio de sesión correctamente
                if (usuarioEncontrado != null && usuarioEncontrado.EstaActivado_usuario)
                {
                    // Se ha realizado el login
                    HttpContext.Session.SetString("email", usuarioEncontrado.Email_usuario);
                    HttpContext.Session.SetString("acceso", usuarioEncontrado.Id_acceso.ToString());

                    return RedirectToAction("Index", "Home");
                }
                // Si la propiedad estaActivado_usuario es false quiere decir que la cuenta no esta activada
                else if (usuarioEncontrado != null && !usuarioEncontrado.EstaActivado_usuario)
                {
                    // La cuenta no ha sido activada
                    ViewData["Mensaje"] = "La cuenta no ha sido activada!!";
                    return View("VistaLogin");
                }
                // Si no es ninguna de las anteriores quiere decir que el email o la contraseña son incorrectas
                else
                {
                    // El email o la contraseña no coinciden
                    ViewData["Mensaje"] = "El email y/o contraseña no son correctos!!";
                    return View("VistaLogin");
                }
            }
            catch (Exception e)
            {
                // Si llega aquí es porque se ha producido un error al iniciar sesión
                // Log
                Util.LogError("LoginController", "LoginUsuario", "Se ha producido un error");

                ViewData["Mensaje"] = "Se ha producido un error. Vuelve a intentarlo más tarde!!";
                return View("VistaLogin");
            }
        }
    }
}

ProyectoFinalDIW/ProyectoFinalDIW/Controllers/RestablecerPasswordController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinalDIW.Models;
using ProyectoFinalDIW.Servicios;

namespace ProyectoFinalDIW.Controllers
{
    /// <summary>
    /// Controlador para gestionar el modificar password
    /// </summary>
    /// autor: Fran Gallego
    public class RestablecerPasswordController : Controller
    {
        // Inicializamos la interfaz Usuario para usar sus métodos
        private UsuarioInterfaz usuarioInterfaz = new UsuarioImplementacion();

        // Inicializamos la interfaz Token para usar sus métodos
        private TokenInterfaz tokenInterfaz = new TokenImplementacion();

        /// <summary>
        /// Método que devuelve la vista para recuperar(modificar) contraseña
        /// </summary>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaRecuperarContrasenya()
        {
            try
            {
                // Log
                Util.LogInfo("RestablecerPasswordController", "VistaRecuperarContrasenya", "Ha entrado en VistaRecuperarContrasenya");

                // Controlamos la sesion
                if (Util.ControlaSesion(HttpContext))
                {
                    // Si el usuario ya ha iniciado sesion redirigimos a la vista home
                    return RedirectToAction("Index", "Home");
                }

                // Devolvemos la vista
                return View();
            }
            catch (Exception)
            {
                // Log
                Util.LogError("RestablecerPasswordController", "VistaRecuperarContrasenya", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que devuelve la vista para cambiar contraseña
        /// </summary>
        /// <returns>Devuelve una vista</returns>
        public IActionResult VistaCambiarContrasenya()
        {
            try
            {
                // Log
                Util.LogInfo("RestablecerPasswordController", "VistaCambiarContrasenya", "Ha entrado en VistaCambiarContrasenya");

                // Controlamos la sesion
                if (Util.ControlaSesion(HttpContext))
                {
                    // Si el usuario ya ha iniciado sesion redirigimos a la vista home
                    return RedirectToAction("Index", "Home");
                }

                // Devolvemos la vista
                return View();
            }
            catch (Exception)
            {
                // Log
                Util.LogError("RestablecerPasswordController", "VistaCambiarContrasenya", "Se ha producido un error");

                // Redirigimos a la vista de error
                return RedirectToAction("VistaError", "Error");
            }
        }

        /// <summary>
        /// Método que realiza el envio de un correo para cambiar las contraseñas
        /// </summary>
        /// <param name="usuario">Objeto UsuarioDTO con el email del usuario</param>
        /// <returns>Devuelve una redireccion</returns>
        [HttpPost]
        public ActionResult RecuperarPassword(UsuarioDTO usuario)
        {
            try
            {
                // Log
                Util.LogInfo("RestablecerPasswordController", "RecuperarPassword", "Ha entrado en RecuperarPassword");

                // Controlamos que el email del usuario sea distinto de null
                if (usuario.Email_usuario == null)
                {
                    ViewData["Mensaje"] = "Tienes que introducir un email!!";
                    return View("VistaRecuperarContrasenya");
                }

                // Si llega aqui es porque se ha introducido un email
                // Llamamos al metodo RecuperaPassword que realiza el envio del correo
                bool ok = usuarioInterfaz.RecuperaPassword(usuario);

                // Controlamos si se ha enviado el correo o no
                if (ok)
                {
                    ViewData["MensajeInfo"] = "Se ha enviado un correo para modificar la contraseña.";
                    return View("VistaRecuperarContrasenya");
                }
                else
                {
                    ViewData["Mensaje"] = "El email introducido no existe!!";
                    return View("VistaRecuperarContrasenya");
                }
            }
            catch (Exception)
            {
                // Log
                Util.LogError("RestablecerPasswordController", "RecuperarPassword", "Se ha producido un error");

                // Si llega aquí es porque se ha producido un error al recuperar password
                // Luego mostramos mensaje de error y devolvemos la vista de recuperar contrasenya
                ViewData["Mensaje"] = "Se ha producido un error. Vuelve a intentarlo más tarde!!";
                return View("VistaRecuperarContrasenya");
            }
        }

        /// <summary>
        /// Método que realiza la modificacion de la contraseña de un usuario
        /// </summary>
        /// <param name="usuario">Objeto UsuarioDTO con el token y la contraseña</param>
        /// <returns>Devuelve una redireccion o la vista en caso de error</returns>
        [HttpPost]
        public ActionResult ModificarPassword(UsuarioDTO usuario)
        {
            try
            {
                // Log
                Util.LogInfo("RestablecerPasswordController", "ModificarPassword", "Ha entrado en ModificarPassword");

                // Guardamos los valores del objeto UsuarioDTO en variables
                string token = usuario.Nombre_usuario;
                string password1 = usuario.Psswd_usuario;
                string password2 = usuario.Email_usuario;

                // Controlamos que los valores sean distintos de null y que las contraseñas coincidan
                if (token == null || password1 == null || password2 == null)
                {
                    ViewData["Mensaje"] = "Tienes que rellenar todos los datos!!";
                    return View("VistaCambiarContrasenya", new { tk = token });
                }
                else if (password1 != password2)
                {
                    TempData["Mensaje"] = "Las contraseñas no coinciden!!";
                    return RedirectToAction("VistaCambiarContrasenya", new { tk = token });
                }

                // Si llega aqui es porque es las contraseñas son iguales
                // Obtenemos el token de la base de datos
                TokenDTO tokenDto = tokenInterfaz.ObtenerToken(token).Result;

                // Controlamos si el token es válido o no
                // Será válido si es distinto de null y la fecha límite del token no se ha pasado
                DateTime fecha = DateTime.Now;
                if (tokenDto == null)
                {
                    TempData["Mensaje"] = "El token no existe!!";
                    return RedirectToAction("VistaCambiarContrasenya", new { tk = token });
                }
                else if (tokenDto.Fch_fin_token < fecha)
                {
                    TempData["Mensaje"] = "El token ha caducado!!";
                    return RedirectToAction("VistaCambiarContrasenya", new { tk = token });
                }

                // Si llega aqui es porque el token es valido
                // Luego llamamos al método modificar password y le pasamos los parámetros
                bool ok = usuarioInterfaz.ModificaPassword(tokenDto, password1);

                if (ok)
                {
                    // Se ha modificado la contraseña correctamente
                    TempData["MensajeCorrecto"] = "La contraseña ha sido actualizada!!";
                    return RedirectToAction("VistaCambiarContrasenya", new { tk = token });
                }
                else
                {
                    TempData["Mensaje"] = "Ha ocurrido un error, vuelve a intentarlo más tarde!!";
                    return RedirectToAction("VistaCambiarContrasenya", new { tk = token });
                }
            }
            catch (Exception)
            {
                // Log
                Util.LogError("RestablecerPasswordController", "ModificarPassword", "Se ha producido un error");

                // Si llega aquí es porque se ha producido un error al modificar password
                // Luego mostramos mensaje de error y devolvemos la vista de recuperar contrasenya
                ViewData["Mensaje"] = "Se ha producido un error. Vuelve a intentarlo más tarde!!";
                return View("VistaCambiarContrasenya", new { tk = usuario.Nombre_usuario });
            }
        }
    }
}

ProyectoFinalDIW/ProyectoFinalDIW/Views/RestablecerPassword/VistaCambiarContrasenya.cshtml
@{
    ViewData["Title"] = "Recuperar Contraseña";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Tienda de Suplementos</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    @*     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script> *@
    <!-- Fin Bootstrap -->
    <!-- CSS -->
    <link rel="stylesheet" href="~/css/styleLogin.css" />
    <!-- Fin CSS -->
    <!-- Font awesome -->
    <link href="https://cdn.jsdelivr.net/gh/eliyantosarage/font-awesome-pro@main/fontawesome-pro-6.5.1-web/css/all.min.css" rel="stylesheet">
    <!-- Fin Font awesome -->
</head>
<body>
    <div class="wrapper">
        <form method="post" asp-controller="RestablecerPassword" asp-action="ModificarPassword" id="formularioMod">
            <h1>Recuperar contraseña</h1>
            <input type="text" name="nombre_usuario" style="display: none" value="" id="idToken">
            <div class="input-box">
                <input type="password" placeholder="Nueva Contraseña" name="psswd_usuario" required>
                <i class="fa-solid fa-envelope"></i>
            </div>
            <div class="input-box">
                <input type="password" placeholder="Introduzca de nuevo la contraseña" name="email_usuario" required>
                <i class="fa-solid fa-envelope"></i>
            </div>

            @if (TempData["Mensaje"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["Mensaje"]
                </div>
            }

            @if (TempData["MensajeCorrecto"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @TempData["MensajeCorrecto"]
                </div>
            }

            <button type="submit" class="boton">Enviar</button>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const urlParams = new URLSearchParams(window.location.search).get("tk");
            const idTokenInput = document.getElementById('idToken');
            idTokenInput.value = urlParams;
        });
    </script>
</body>
</html>

ProyectoFinalDIW/ProyectoFinalDIW/Views/RestablecerPassword/VistaRecuperarContrasenya.cshtml
@{
    ViewData["Title"] = "Recuperar Contraseña";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Tienda de Suplementos</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
@*     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script> *@
    <!-- Fin Bootstrap -->
    <!-- CSS -->
    <link rel="stylesheet" href="~/css/styleLogin.css" />
    <!-- Fin CSS -->
    <!-- Font awesome -->
    <link href="https://cdn.jsdelivr.net/gh/eliyantosarage/font-awesome-pro@main/fontawesome-pro-6.5.1-web/css/all.min.css" rel="stylesheet">
    <!-- Fin Font awesome -->
</head>
<body>
    <div class="wrapper">
        <form method="post" asp-controller="RestablecerPassword" asp-action="RecuperarPassword">
            <h1>Recuperar contraseña</h1>
            <div class="input-box">
                <input type="email" placeholder="Email" name="email_usuario" required>
                <i class="fa-solid fa-envelope"></i>
            </div>

            <div class="remember-forgot" style="margin-bottom: 2px;">
                <p>¿Has recordado la contraseña? <a asp-controller="Login" asp-action="VistaLogin" style="font-weight: 600;">Pulsa aquí</a></p>
            </div>

            @if (ViewData["Mensaje"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @ViewData["Mensaje"]
                </div>
            }

            @if (ViewData["MensajeInfo"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @ViewData["MensajeInfo"]
                </div>
            }

            <button type="submit" class="boton">Enviar</button>
        </form>
    </div>
</body>
</html>